wname: test every pr
on:
 workflow_dispatch:
 pull_request:
   contents: read
   pull-request: read
jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       -name: Cheackout
        uses: actions/checkout@v3
       -name: setup jdk
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle
        -name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
        -name: gradlew test
         run: ./gradlew test         
